# Site settings
title: Richard Fulop
email: richardbfulop@gmail.com
description: > # 
  Exploring the possibilites that modern technology provides us, one line of code at a time
baseurl: ""
url: "http://richardfulop.me" # the base hostname & protocol for your site
twitter_username: richiebful
github_username:  richiebful

# Build settings
markdown: kramdown
