# Site settings
title: Richard Fulop
email: richardbfulop@gmail.com
description: > # 
  A blog about a variety of topics ranging from computer science to politics to linguistics to artificial intelligence and back.
baseurl: "/blog/"
url: "http://richiebful.github.io" # the base hostname & protocol for your site
twitter_username: richiebful
github_username:  richiebful

# Build settings
markdown: kramdown
