# Site settings
title: Richard Fulop
email: richardbfulop@gmail.com
description: > # 
  This is literally a dumping ground for all of my interests.
baseurl: ""
url: "http://richardfulop.me" # the base hostname & protocol for your site
twitter_username: richiebful
github_username:  richiebful

# Build settings
markdown: kramdown
